### ISSUE TITLE
MovingWorld creates config files in the wrong place with weird names.

### ISSUE THREAD

**Issue by Sinhika** [darkevilmac/MovingWorld#1]
In the base directory of a minecraft instance, it created the file "\MovingWorld\Main.cfg".  In the config directory, it created a directory "MovingWorld\MetaRotation". I am running on a Linux system, and you seem to have hard-coded Windows file names in your program. That is a mistake.

The problem would be lines 47-48 in MovingWorld.java:

    String configFolder = e.getSuggestedConfigurationFile().toString().substring(0, e.getSuggestedConfigurationFile().toString().lastIndexOf("\\") + 1);
     File mConfigFile = new File(configFolder + "\\MovingWorld\\Main.cfg");

Those lines are not correct and not portable. Instead:

    File configFolder =  new File(e.getModConfigurationDirectory(), "MovingWorld");
    File mConfigFile = new File(configFolder, "Main.cfg");

Should do the trick, in a completely portable manner that works on Linux and OSX systems. For an example of a working implementation, see the GetConfig() method in https://github.com/Sinhika/akkamaddiCore/blob/master/java/akkamaddi/api/core/ASettings.java.

You have a similar issue in MetaRotations.java, in the registerMetaRotationFile() method. Same fix. Look up the File() constructor in the Java API documentation--one option is to glue a directory name and a file name together for you portably. Use it.

**Comment by darkevilmac** [comment]
Cheers, I don't work with the java files api that much which is why I made that mistake. I'll go ahead and adjust accordingly then mark the issue as fixed in a few minutes.

**Comment by Sinhika** [comment]
Well, I only learned this from reading someone else's well-written code. ;-)

**Comment by Sinhika** [comment]
Tested new release. It now puts the Main.cfg in the correct "MovingWorld" folder on Linux.
However, the mrot stuff is still in a folder with a funny name ('\MovingWorld\MetaRotation').

**Comment by darkevilmac** [comment]
I really don't know how I missed that, bumping version and pushing.
