### ISSUE TITLE
Moving World 1.8-alpha-3.3 doesn't satisfy dependency requirement for Archimedes Ships Plus 1.8 Alpha 3.3

### ISSUE THREAD

**Issue by kreezxil** [darkevilmac/MovingWorld#12]
Issue: Moving World 1.8-alpha-3.3 doesn't satisfy dependency requirement for Archimedes Ships Plus 1.8 Alpha 3.3

crash report:
https://gist.github.com/51e2b163d3ab52d9ea5c

fml server latest:
https://gist.github.com/84e08b947918a147341f

**Comment by darkevilmac** [comment]
Hmm, MovingWorldCore doesn't seem to be loaded in at all in that instance. I'm unable to recreate the issue with the latest forge version as well.
