### ISSUE TITLE
I have AS+ working in client, but not on local forge server

### ISSUE THREAD

**Issue by dustin-cramer** [darkevilmac/MovingWorld#13]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 9/3/15 2:30 PM
Description: Exception in server tick loop

Missing Mods:
	MovingWorld : any

net.minecraftforge.fml.common.MissingModsException: Mod ArchimedesShipsPlus (Archimedes' Ships Plus) requires [MovingWorld]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:237)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:487)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 3.16.0-38-generic
	Java Version: 1.8.0_45-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1975542880 bytes (1884 MB) / 2595749888 bytes (2475 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4096m -Xms2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1506 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1506-universal.jar) 
	U	Forge{11.14.3.1506} [Minecraft Forge] (forge-1.8-11.14.3.1506-universal.jar) 
	U	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	U	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	U	AnimalsPlus{1.4} [Animals Plus] (animalsplus-1.4.jar) 
	U	antiqueatlas{4.2.7-1.8} [Antique Atlas] (antiqueatlas-4.2.7-1.8.jar) 
	U	ArchimedesShipsPlus{MC1.8-V1.8} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8-V1.8.jar) 
	U	cabinets3{version} [Cabinets Reloaded] (Cabinets Reloaded-3.0.45.jar) 
	U	ForgeEssentials{1.8.3} [Forge Essentials] (forgeessentials-1.8-1.8.3.35-server.jar) 
	U	fusionutil{0.1} [FusionUtil] (FusionUtil-0.1.6.jar) 
	U	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	U	landdefender{0.5.1} [Land Defender] (landdefender-0.5.1.jar) 
	U	MCA{1.8-5.0.7.1} [Minecraft Comes Alive] (MCA-1.8-5.0.7.1-universal.jar) 
	U	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8-build1(1.8).jar) 
	U	RadixCore{1.8-2.0.4} [RadixCore] (RadixCore-1.8-2.0.4-universal.jar) 
	U	corerm{1.2c} [RikMuld's Core] (RikMuldsCore_1.2c.jar) 
	U	camping{2.2e} [The Camping Mod 2] (TheCampingMod_2.2e.jar) 
	U	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.8-6.1.1-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

-----------

Sorry if this isn't the format you wanted, but I'm really strapped for time and thought you should know your library isn't liked by a LAN forge server.

I even tried to copy the configs/files from my client to the local server and also tried to remove them to get new defaults, no change.

**Comment by darkevilmac** [comment]
This was fixed  a while back with some mixins updates.
