### ISSUE TITLE
Crash in compiled version due to Mixins

### ISSUE THREAD

**Issue by darkevilmac** [darkevilmac/MovingWorld#20]
This is the relevant snippet from the crash log: http://hastebin.com/upipotileh.avrasm

Really not sure why this is happening as everything on my build.gradle seems to be correct from what I can tell. This wasn't happening in 1.8 though so it must be something incorrect with my usage of the new MixinGradle plugin.

@Mumfrey if you have some free time would you be willing to take a look?

**Comment by Mumfrey** [comment]
You're defining the refmap [here](https://github.com/darkevilmac/MovingWorld/blob/master/build.gradle#L40) as `"mixins.movingworld.json"` but [in your actual config file](https://github.com/darkevilmac/MovingWorld/blob/master/src/main/resources/mixins.movingworld.json#L10) your refmap is named `"movingworld.mixin.refmap.json"` Firstly you just need to correct the name of your refmap in your `build.gradle`.

Secondly, it doesn't look like you've actually specified to obfuscate your shadow jar. To obfuscate your shadow jar you need to use something like:

```groovy
reobf {
    shadowJar {
        mappingType 'NOTCH'
    }
}
````

For more details see my `build.gradle` [here](http://develop.liteloader.com/liteloader/LiteLoader/blob/master/build.gradle) which shows how to set up obfuscation for multiple jars using mixingradle.

**Comment by darkevilmac** [comment]
Thanks, other quick question as I'm not overly familiar with the mappings system. Just as a general rule is it best to use notch mappings on builds outside of dev environments and use searge for builds to be used inside a dev environment?
