### ISSUE TITLE
Mounting ships causes crash

### ISSUE THREAD

**Issue by FaeyUmbrea** [darkevilmac/MovingWorld#27]
Soo, I managed to make the ship assemble, but now, mounting it crashes the servers sponge installation, I suspect movingworld being the culprit based on the report, so I opened the Issue here.

I do have the crashreport, but I can't seem to find the log files and I don't want to crash the server again.

Crashreport: http://pastebin.com/guVbAzgm

**Comment by darkevilmac** [comment]
Open the issue on sponge, I can't see anything from MovingWorlds codebase that causes this, they might not be checking if something's null or not because it's a NPE.
