### ISSUE TITLE
Crash on Client Startup

### ISSUE THREAD

**Issue by zacklmoore** [darkevilmac/MovingWorld#44]
I have a bunch of mods installed so I'm not completely sure this is coming from this one but it appears so from the logs. The client doesn't make it to the loading screen. Forge Version: 14.21.1.2413

Let me know if there's anything else I can provide to help debug this!

Crash Log:

https://pastebin.com/1j2q7BJw

EDIT: Ah just saw I should put issues in Davinci's Vessels? If so I can move this there. I'll give it a couple days first though.

**Comment by darkevilmac** [comment]
Not much I can do but remove the unused Mixin, doesn't do anything at this point anyway.
