### ISSUE TITLE
String should use equals

### ISSUE THREAD

**Issue by liach** [darkevilmac/MovingWorld#47]
https://github.com/elytra/MovingWorld/blob/1c547d75d9e681473cbc04a58dc6b803d5ef19fa/src/main/java/com/elytradev/movingworld/common/asm/mixin/core/block/property/MixinPropertyInteger.java#L16

**Comment by exaskye** [comment]
~~high quality darkevilmac code~~

**Comment by darkevilmac** [comment]
It ages like a fine wine.
