### ISSUE TITLE
[1.12.2] Crash on Game Start - Null Pointer Exception

### ISSUE THREAD

**Issue by MasterEnderman** [darkevilmac/MovingWorld#51]
Crah Report: https://pastebin.com/3EwGcn9y
Forge: 14.23.2.2618
MovingWorld: 6.342
Davincis Vessels: 6.340

**Comment by CcytherR** [comment]
Same crash i think https://pastebin.com/E9FinxNe

**Comment by brisingraerowing** [comment]
I get the same crash as well.

**Comment by SonnyLonglegs** [comment]
I get the same crash.

**Comment by SonnyLonglegs** [comment]
Apparently, according to the next issue down, it's caused by Redstone++.

**Comment by exaskye** [comment]
Appears to be the same exception, yes.

Closing as a duplicate of #50
