### ISSUE TITLE
Mod Incompatibility with Chisels and Bits

### ISSUE THREAD

**Issue by TzenYasuaki** [darkevilmac/MovingWorld#52]
Minecraft Version: 1.10.2

Forge Version: 12.18.3.2185

Davincis Vessels Version: 0006

Moving World Version: 0007

Crash Report:

https://gist.github.com/TzenYasuaki/db4b0d222b0f284c6be051ce7c9ef268#file-crash-2018-02-19_08-03-46-client-txt

Hey there, i tried to assemble a ship which includes Microblocks, but it crashed. I hope you can help me with this Problem :D.

Greetings Tzen

**Comment by Tri0de** [comment]
I believe this has something to do with the FastTileEntityRenderer vertex buffer. The .build() method was called twice.

**Comment by TzenYasuaki** [comment]
I have no knowlegde in java or any other IT. :D Is it fixable ?

**Comment by TzenYasuaki** [comment]
I have no knowlegde in Java or any other form of IT. Is it fixable?

**Comment by Tri0de** [comment]
Well I fixed it with VW, so I'll assume its fixable 😏

**Comment by darkevilmac** [comment]
I'm no longer supporting 1.10, the last release I made for it was over a year ago.

**Comment by TzenYasuaki** [comment]
hmm sad ok thanks for ur awnser
