### ISSUE TITLE
MovingWorld Crash

### ISSUE THREAD

**Issue by Diamondman121314** [darkevilmac/MovingWorld#73]
After updating to the latest MovingWorld, it seems to crash.

https://gist.github.com/Diamondman121314/c325f13e0410b3c92cc4d122180ccb2d#file-gistfile1-txt-L666

**Comment by Diamondman121314** [comment]
After finally being able to look into why, Concrete isn't in the MovingWorld jar.

**Comment by darkevilmac** [comment]
Fixed, new build has been submitted. Curse usually approves after a few minutes for me.
