### ISSUE TITLE
Trying to build 1.14.3 - Getting Compound error

### ISSUE THREAD

**Issue by umbecanessa** [darkevilmac/MovingWorld#77]
Yo! I'm trying something simple such as cloning the branch 1.14.3 and build it, it works easy for Da Vinci's vessel, but with Moving worlds build works fine, but when launching MC I get: _**Exception caught during firing event: com/tridevmc/compound/network/core/CompoundNetwork**_

Any idea?

**Comment by darkevilmac** [comment]
Anything past 1.12 is not marked as stable. Things will break.

The buildscript is not complete and the exported jars are very unlikely to work.
