### ISSUE TITLE
CoreMod?

### ISSUE THREAD

**Issue by codexcode** [darkevilmac/MovingWorld#8]
Hello. I've tried the Alpha2 build for 1.8 and would love to report a bug. It's conflicting with minecraft.jar itself. Saying it needs to be a coremod. If that's the case, please do update the wiki and the forum page. However, if it isn't a bug, I'm glad I could bring this to your attention.

Chao.

**Comment by darkevilmac** [comment]
Could you clarify?

Is this an issue with compiled builds or the dev environment?

If it's in the dev environment simply add the parameter for the codemod location to the VM ARGS (Automatically done if you're using IntelliJ Idea).

If it's an issue with the built version available on curseforge or minecraftforums, could you let me know your forge version?

**Comment by darkevilmac** [comment]
Closing until further notice as you haven't explained the issue in more depth.
